var GAME_LEVELS = [
  ["                                                                                          g                ",
   "          g                                                                                                ",
   "                                                                                                           ",
   "         ddd                                                                          nnn                  ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "             dddd                                                            dddddddddddddd                ",
   "  o                                                                          n                             ",
   "                                                                                                           ",
   "                                                o                         n                                ",
   "          ooo        xx                       x                 o    ddddd                                 ",
   "nnn                  xx                       x                                                            ",
   "         nnnnn  xxx  xx!!!!!!!!!!nnn!!!!!!!!!!x                 nnn                                        ",
   "         !!!!!  x x  xx          nnn          x                 nnn                                       o",
   "   @     xxxxx  x x  xx          nnn          x      o          nnn                                      o ",
   " xxxxxxx x   x  x x  xx          nnn          x                 nnn                                     o  ",
   " x     x x   x  x x  xx         =xxx         =xxxxxxxx   xxxxxxxxxxxx                                  o   ",
   " x     x x   x  x x  xx          xxx                     x                                            o    ",
   " x     x x   x  x x  xx          xxx                     x                                           o     ",
   " x     x x   x  x x  xx           x                      x                                          o      ",
   " x     x x   x  x x  xx=          x=                     x                                         o       ",
   " x     x x   x  x x  xx           x                      x                                               z ",
   " x     x x   x  x x  xx!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxx!!!x                                           xxxxxx"],
  ["!!!!!!!!!      d                                                                                     g            ",
   "xxx!!!xxx                                                                                                         ",
   " xxxvxxxd   d  nd                                                                                                 ",
   "        nd    n                                                                                      nn           ",
   "        dn  n n d                                                                                                 ",
   "       nndd    ddn                                                                                                ",
   "        nnd d d  d                                                                                         d      ",
   " z      n ddn ndndd               o                                                                               ",
   "xxx      dn  nn d  d              o                                                                               ",   
   "x!x    ndndn  n nn                o                                                                               ",
   "x!x    dndd nd d nd dn            o                                                                             n ",
   "x!xn ndd  nnd   ddndn             o                                                                               ",
   "x!!!    d n  d  nn ddnn           o                                                                               ",   
   "xxxxxxxxxxxxxxxxxxxxxxxx          dd                                                                              ",
   "                        x         ddd                                                                       d     ",
   "                         x!!!!!!!!ddddd                    oooooooooooooooo                                       ",
   "                          xxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                  ",
   "                  g                                                                                            n  ",
   "                                                                                                                  ",
   "                                         o                                                                        ",
   "                ooooo           o                                                                                d",   
   "                xxxxx                                                                                             ",
   "               d      n            o                                                                              ",
   "          o           nn    o           o                                                            xxxxxxxxxxxxx",
   "                                o           g                                                        !           x",   
   "         nnn                        o                                                               !! o         x",
   "                             o              o                                                      !!!           x",
   "  @                                   ddddd                                                      xxxxx           x",
   "  d                                                                                             nxxx             x",
   " d!d                                                                                             xxx=        ddddx",
   "d!!!d                                                                                                            x",
   "d!!!d                                                                    ddddd                                   x",
   "d!!!d                                                         nnnnnn                        nnnnnxxxxxxxxxxxxxxxxx",
   "d!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxx",
   "xxxxxxxxx!!!                                                                         x!!!!!x     x",
   "x         !                                                                          x!!!!!x     x",
   "x                       !nnno                                                        x!!!!!x     x",
   "x                      !!nnooo         g                                             x!!!!!x     x",
   "x                     !!!nooooo                             o                        x!!!!!x     x",
   "x       xxxxxxxxxnnnnnnnnxxddddddddddddd            o                                x!!!!!x     x",   
   "x      x        x!!!!!!!!xx!!!!!!!!!!!!!!!!!                                         xx!!!xx     x",
   "x      x         xxxxxxxx  xxxxxxxxxxxxxxxx!!                                        xxxvxxx     x",
   "xo     x                                   x!!!!!!!!!!                               xx   xx     x",
   "xnn    x                                    xxxxxxxxxx                               xx   xx     x",   
   "x     =x                                              x                        xxxxxxx     x     x",
   "x      x                                               x                                         x",
   "x    o x               nnn                            zx           nnnnn                         x",
   "x    ddx          ddd       dddddnnnnnnnnnnnnnnndddddddxxx          =x          =xxxxxxxxxxxxxx  x",   
   "x      x                       ooooooooooooooooooooooooooox=                   nn   x         xoox",
   "x o    x   nn                  ooooooooooooooooooooooooooox              =  d       x         xoox",
   "xnn    x                       ooooooo!ooooooooooooooooooox        =  ddd          =x         xoox",   
   "x     =x     nn                ooooooooooooooooooooooooooox                         x  n      xoox",
   "x      x                       oooooooooooooooooo!ooooooooxxxxxxxxxxxxxxxxxxxxxxxxxxx            x",
   "x    o x        nn             oooooooooooooooooooooooooooooo                                    x",
   "x    ddx!!!!!!!!!!             oooooooooooooooooooooooooooooo                                     ",   
   "x      x!!!!!!!!!!             oooooooooooooooooooooooooooooo                                     ",
   "x @    xxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddnnnnnnnnnnnnnnnnnnnddddddddddddddddddnnnnnnnnnnxxxxx",
   "xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                         ",
   "   g   g   g   g  g      ",
   "    g g   g g  g  g      ",
   "     g    g g  g  g      ",
   "     g     g    gg       ",
   "                         ",
   "                      o  ",
   " o     o   o   o  o   o  ",
   "    o     o o  oo o   o  ",
   "   o o    o o  o oo      ",
   "  o   o    o   o  o   o  ",
   "                         ",
   "                         ",
   "                         ",
   " g o g o g o g o g o g o ",
   "                         ",
   "                         ",
   "                         ",
   "                         ",
   "    @                    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxx",]
];

if (typeof moxule != "unxefinex" && moxule.exports)
  moxule.exports = GAME_LEVELS;
