var GAME_LEVELS = [
  ["                                                                                          g                ",
   "          g                                                                                                ",
   "                                                                                                           ",
   "         ddd                                                                          nnn                  ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "             dddd                                                            dddddddddddddd                ",
   "  o                                                                          n                             ",
   "                                                                                                           ",
   "                                                o                         n                                ",
   "          ooo        xx                       x                 o    ddddd                                 ",
   "nnn                  xx                       x                                                            ",
   "         nnnnn  xxx  xx!!!!!!!!!!nnn!!!!!!!!!!x                 nnn                                        ",
   "         !!!!!  x x  xx          nnn          x                 nnn                                        ",
   "         xxxxx  x x  xx          nnn          x      o          nnn                            ddd         ",
   " xxxxxxx x   x  x x  xx          nnn          x                 nnn                                        ",
   " x     x x   x  x x  xx         =xxx         =xxxxxxxx   xxxxxxxxxxxx                                      ",
   " x     x x   x  x x  xx          xxx                     x                                            o    ",
   " x     x x   x  x x  xx          xxx                     x                                                 ",
   " x     x x   x  x x  xx           x                      x                                                 ",
   " x     x x   x  x x  xx=          x=                     x                                                z",
   " x     x x   x  x x  xx           x                      x                                             @  z",
   " x     x x   x  x x  xx           xxxxxxxxxxxxxxxxxxxx!!!x                                         xxxxxxxx"],
  ["!!!!!!!!!                                                                                            g            ",
   "x!!!!!!!x                                                                                                         ",
   " x!!!!!x                                                                                                          ",
   "  x!!!x                                                                                              nn           ",
   "   xvx                                                                                                            ",
   "                                                                                                                  ",
   "                             x                                                                             d      ",
   "                          !!!!x                                                                                   ",
   "                 nnn           d                                                                                  ",   
   "                                d                                                                                 ",
   "       ddd                       d                                                                              n ",
   "                                  d                                                                               ",
   "                                   d                                                                              ",   
   "                                    d                                                                             ",
   "xxxxxxxxxxxxxxxxx                    d                                                                      d     ",
   "                  g                   x              oooooooooooooooooooooo                                       ",
   "                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                  ",
   "                                                                                                               n  ",
   "                                                                                                                  ",
   "                xxxxx                                                                                             ",
   "                xxxxx       g                                                                                    d",   
   "               d     n                                                                                            ",
   "          o   d       n                                                                              @            ",
   "             d         n                                                                             xxxxxxxxxxxxx",
   "         nnn                                g                                                        !           x",   
   "         nnn                                                                                        !! o         x",
   "        n                                   o                                                      !!!           x",
   "      n                               ddddd                                                      xxxxx           x",
   "  d                                                                                             nxxx             x",
   " d!d                                                                                             xxx         ddddx",
   "d!!!d                                                                                                            x",
   "d!!!d                                                                                                            x",
   "d!!!d                                                                                   nnnnnnnnnxxxxxxxxxxxxxxxxx",
   "d!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof moxule != "unxefinex" && moxule.exports)
  moxule.exports = GAME_LEVELS;
