var GAME_LEVELS = [
  ["                                                                                          g                ",
   "          g                                                                                                ",
   "                                                                                                           ",
   "         ddd                                                                          nnn                  ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "             dddd                                                            dddddddddddddd                ",
   "  o                                                                          n                             ",
   "                                                                                                           ",
   "                                                o                         n                                ",
   "          ooo        xx                       x                 o    ddddd                                 ",
   "nnn                  xx                       x                                                            ",
   "         nnnnn  xxx  xx!!!!!!!!!!nnn!!!!!!!!!!x                 nnn                                        ",
   "         !!!!!  x x  xx          nnn          x                 nnn                                        ",
   "         xxxxx  x x  xx          nnn          x      o          nnn                            ddd         ",
   " xxxxxxx x   x  x x  xx          nnn          x                 nnn                                        ",
   " x     x x   x  x x  xx         =xxx         =xxxxxxxx   xxxxxxxxxxxx                                      ",
   " x     x x   x  x x  xx          xxx                     x                                            o    ",
   " x     x x   x  x x  xx          xxx                     x                                                 ",
   " x     x x   x  x x  xx           x                      x                                                 ",
   " x     x x   x  x x  xx=          x=                     x                                                z",
   " x     x x   x  x x  xx           x                      x                                            @   z",
   " x     x x   x  x x  xx           xxxxxxxxxxxxxxxxxxxx!!!x                                           xxxxxx"],
  ["!!!!!!!!!      d                                                                                     g            ",
   "x!!!!!!!x                                                                                                         ",
   " x!!!!!xd   d  nd                                                                                                 ",
   "  x!!!x nd    n                                                                                      nn           ",
   "   xvx  dn  n n d                                                                                                 ",
   "       nndd    ddn                                                                                                ",
   "        nnd d d  d                                                                                        d      ",
   " z@     n ddn ndndd                                                                                               ",
   "xxx      dn  nn d  d                                                                                              ",   
   "x!x    ndndn  n nn                                                                                                ",
   "x!x d  dndd nd d nd dn                                                                                          n ",
   "x!xn ndd  nnd   ddndn                                                                                             ",
   "x!!!    d n  d  nn ddnn           o                                                                               ",   
   "xxxxxxxxxxxxxxxxxxxxxxxx          dd                                                                              ",
   "                        x         ddd                                                                       d     ",
   "                         x!!!!!!!!ddddd                    oooooooooooooooo                                       ",
   "                          xxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                  ",
   "                  g                                                                                            n  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                ooooo                                                                                            d",   
   "                xxxxx                                                                                             ",
   "               d      n                                                                                           ",
   "          o           nn    o           o                                                            xxxxxxxxxxxxx",
   "                                o           g                                                        !           x",   
   "         nnn                                                                                        !! o         x",
   "                                            o                                                      !!!           x",
   "                                      ddddd                                                      xxxxx           x",
   "  d                                                                                             nxxx             x",
   " d!d                                                                                             xxx=        ddddx",
   "d!!!d                                                                                                            x",
   "d!!!d                                                                    ddddd                                   x",
   "d!!!d                                                         nnnnnn                        nnnnnxxxxxxxxxxxxxxxxx",
   "d!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",   
   "                                                                                                                  ",
   "x                                                                                                                 ",
   "x     dddd                                                                                                        ",
   "x      d                                                                                                          ",   
   "xo     x                                                                                                          ",
   "nnn    x                                                                                                          ",
   "x=     x                                                                                                          ",
   "x      x                                                                                                          ",
   "x    o x                                                                                                          ",
   "x   dddx                                                                                                          ",
   "xo     x                                                                                                          ",
   "nnn    x                                                                                                          ",   
   "x     =x                                                                                                          ",
   "x      x                                                                                                          ",
   "x    o x                                                                                                          ",
   "x    ddx                                                                                                          ",   
   "x      x                                                                                                          ",
   "x @   ox                                                                                                          ",
   "xxxxxxxxxxxxxxxxxxxxx                                                                                             "],
  ["                         ",
   "   g   g   g   g  g      ",
   "    g g   g g  g  g      ",
   "     g    g g  g  g      ",
   "     g     g    gg       ",
   "                         ",
   "                      o  ",
   " o     o   o   o  o   o  ",
   "    o     o o  oo o   o  ",
   "   o o    o o  o oo      ",
   "  o   o    o   o  o   o  ",
   "                         ",
   "                         ",
   "                         ",
   " g o g o g o g o g o g o ",
   "                         ",
   "                         ",
   "                         ",
   "                         ",
   "    @                    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxx",]
];

if (typeof moxule != "unxefinex" && moxule.exports)
  moxule.exports = GAME_LEVELS;
